# Generated by Django 3.2.3 on 2021-06-09 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales_manager', '0009_book_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='text',
            field=models.TextField(blank=True, null=True),
        ),
    ]
