# Generated by Django 3.2.3 on 2021-06-09 12:01

from django.db import migrations, models
import sales_manager.utils


class Migration(migrations.Migration):

    dependencies = [
        ('sales_manager', '0010_alter_comment_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to=sales_manager.utils.upload_to),
        ),
    ]
