# Generated by Django 3.2.3 on 2021-06-08 09:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('hotel', '0004_booking'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookedRoom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='RoomKind',
            fields=[
                ('name', models.CharField(max_length=10, primary_key=True, serialize=False)),
            ],
        ),
        migrations.RenameField(
            model_name='room',
            old_name='profile',
            new_name='description',
        ),
        migrations.RemoveField(
            model_name='room',
            name='book_room',
        ),
        migrations.RemoveField(
            model_name='room',
            name='date_creation',
        ),
        migrations.RemoveField(
            model_name='room',
            name='designer',
        ),
        migrations.RemoveField(
            model_name='room',
            name='number_of_seats',
        ),
        migrations.RemoveField(
            model_name='room',
            name='occupation',
        ),
        migrations.RemoveField(
            model_name='room',
            name='title',
        ),
        migrations.DeleteModel(
            name='Booking',
        ),
        migrations.AddField(
            model_name='bookedroom',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='booked', to='hotel.room'),
        ),
        migrations.AddField(
            model_name='bookedroom',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='booked', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='room',
            name='kind',
            field=models.ForeignKey(default=111, on_delete=django.db.models.deletion.CASCADE, to='hotel.roomkind'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='room',
            name='user',
            field=models.ManyToManyField(related_name='room', through='hotel.BookedRoom', to=settings.AUTH_USER_MODEL),
        ),
    ]
